### ISSUE TITLE
Use of deprecated python 2.7 does worry in long term

### ISSUE THREAD

**Issue by ssbarnea** [mozillazg/mirror-hg-repo#19]
As github already deprecated python 2.7 and planning to soon remove it, the long term viability of this action is in question.

```
  Error: DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
```

**Comment by mozillazg** [comment]
@ssbarnea The latest version (`mozillazg/mirror-hg-repo@v2`) has been changed to use Python 3.

```
- uses: actions/setup-python@v4
  with:
    python-version: '3.10'

- name: mirror https://foss.heptapod.net/pypy/cffi
  uses: 'mozillazg/mirror-hg-repo@v2'
  with:
    source-hg-repo-url: 'https://foss.heptapod.net/pypy/cffi'
    destination-git-repo-owner: 'mozillazg'
    destination-git-repo-name: 'cffi'
    destination-git-personal-token: '${{ secrets.PERSONAL_GIT_TOKEN }}'
```
